name: 'WorkFlow Tools'
description: 'Tools for deploy app using runner seft-hosted to infra AWS'
inputs:
  action:  
    description: 'Acción que define que actividad realizar'
    required: true
    default: 'default'
  origen:  
    description: 'Directorio origen'
    required: false
    default: 'public'
  destino:  
    description: 'Directorio destino'
    required: false
    default: 'artefactos'
  namespace:  
    description: 'Namespace app'
    required: false
    default: 'nombre-namespace'
  branch:  
    description: 'Branch deploy'
    required: false
    default: 'devel'
  app_name:  
    description: 'Name app'
    required: false
    default: 'app'
  repo:  
    description: 'Name repo'
    required: false
    default: 'ecr'
  token:  
    description: 'Token github'
    required: false
    default: 'xxxxxxx'
  deployment:  
    description: 'Name deployment'
    required: false
    default: 'xxxxxxx'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'