name: 'WorkFlow Tools'
description: 'Tools for deploy app using runner seft-hosted to infra AWS'
inputs:
  action:  
    description: 'Variable to define action to realice'
    required: true
    default: 'default'
  namespace:  
    description: 'Namespace on cluster'
    required: false
    default: 'nombre-namespace'
  branch:  
    description: 'Branch to deploy'
    required: false
    default: 'devel'
  ecr:  
    description: 'Name repo ecr'
    required: false
    default: 'ecr'
  token_github:  
    description: 'Token github'
    required: false
    default: 'AAAAABBBBB'
  deployment:  
    description: 'Name deployment'
    required: false
    default: 'Wherever DEPLOY'
  cluster:  
    description: 'Name cluster'
    required: false
    default: 'default'
  github_ref:  
    description: 'Github REF'
    required: false
    default: '0.0.0'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node12'
  main: 'index.js'

